import { Button, VerticalBox , LineEdit, HorizontalBox} from "std-widgets.slint";
export component Dialog {
    out property <float> x_shift: x_in.text.to-float();
    out property <float> y_shift: y_in.text.to-float();

    callback close();

    width: 300px;
    VerticalBox {
        alignment: start;
        Text {
            text: "Enter values to shift the\npipes by.";
            //horizontal-alignment: center;
        }
        Text {
            text: "Negative X shifts to the left \nPositive to the Right";
        }
        Text {
            text: "Negative Y shifts up\nPositive down";
        }

        HorizontalBox {
            Text {
                text: "X Shift:";
                vertical-alignment: center;
            }
            x_in := LineEdit {
                text: 0;
            }
        }

        HorizontalBox {
            Text {
                text: "Y Shift:";
                vertical-alignment: center;
            }
            y_in := LineEdit {
                text: 0;
            }
        }

        HorizontalLayout {
            alignment: center;
            Button {
                text: "Accept";

                clicked => { close() }
            }
        }
    }
}
